(function(){
const Lab=window.SSTLab,V=Lab.Vec;
function sanitizeClosed(points){const pts=points.filter(p=>p.length>=3&&p.every(Number.isFinite)).map(p=>[+p[0],+p[1],+p[2]]);if(pts.length>3){const scale=Math.max(...pts.map(p=>V.norm(p)),1);if(V.dist(pts[0],pts[pts.length-1])<1e-10*scale)pts.pop()}return pts}
function closedLength(points){let L=0;for(let i=0;i<points.length;i++)L+=V.dist(points[i],points[(i+1)%points.length]);return L}
function uniformResampleClosed(input,n){const points=sanitizeClosed(input);if(points.length<4)throw new Error("Need at least 4 valid centerline points.");n=Math.max(16,Math.floor(n));const seg=[],cum=[0];for(let i=0;i<points.length;i++){const d=V.dist(points[i],points[(i+1)%points.length]);seg.push(d);cum.push(cum[cum.length-1]+d)}const L=cum[cum.length-1];if(!(L>0))throw new Error("Centerline has zero total length.");const out=[];let k=0;for(let j=0;j<n;j++){const target=L*j/n;while(k<seg.length-1&&cum[k+1]<=target)k++;const d=seg[k],u=d>0?(target-cum[k])/d:0,p0=points[k],p1=points[(k+1)%points.length];out.push([p0[0]+u*(p1[0]-p0[0]),p0[1]+u*(p1[1]-p0[1]),p0[2]+u*(p1[2]-p0[2])])}return out}
function generateTrefoil(R,a,n){const pts=[],denseN=Math.max(4*n,1024);for(let i=0;i<denseN;i++){const t=2*Math.PI*i/denseN,A=R+a*Math.cos(3*t);pts.push([A*Math.cos(2*t),A*Math.sin(2*t),a*Math.sin(3*t)])}return uniformResampleClosed(pts,n)}
function differentialGeometry(points){const n=points.length;if(n<8)throw new Error("Need at least 8 points for periodic differential geometry.");const L=closedLength(points),h=L/n,curv=new Array(n),tors=new Array(n),s=new Array(n),speed=new Array(n),at=i=>points[(i+n)%n];for(let i=0;i<n;i++){const pm2=at(i-2),pm1=at(i-1),p0=at(i),pp1=at(i+1),pp2=at(i+2);const r1=[(pp1[0]-pm1[0])/(2*h),(pp1[1]-pm1[1])/(2*h),(pp1[2]-pm1[2])/(2*h)];const r2=[(pp1[0]-2*p0[0]+pm1[0])/(h*h),(pp1[1]-2*p0[1]+pm1[1])/(h*h),(pp1[2]-2*p0[2]+pm1[2])/(h*h)];const r3=[(pp2[0]-2*pp1[0]+2*pm1[0]-pm2[0])/(2*h*h*h),(pp2[1]-2*pp1[1]+2*pm1[1]-pm2[1])/(2*h*h*h),(pp2[2]-2*pp1[2]+2*pm1[2]-pm2[2])/(2*h*h*h)];const c12=V.cross(r1,r2),v=V.norm(r1),c2=V.dot(c12,c12);speed[i]=v;curv[i]=V.norm(c12)/Math.max(v**3,1e-300);tors[i]=c2>1e-28?V.dot(c12,r3)/c2:0;s[i]=i*h}return{points,n,lengthUnit:L,dsUnit:h,sUnit:s,curvatureUnit:curv,torsionUnit:tors,speed}}
Lab.Geometry={generateTrefoil,sanitizeClosed,closedLength,uniformResampleClosed,differentialGeometry};
})();
